server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3

# Logs detalhados
logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.retry=DEBUG
logging.level.org.springframework.rabbit=DEBUG 